steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=$TAG_NAME','-e "SPRING_PROFILES_ACTIVE=$PROFILE"', '.']
images: ['$TAG_NAME']