spring:
  kafka:
    bootstrap-servers:  10.132.126.155:32771
    consumer:
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.LongSerializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArraySerializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      properties:
        max.block.ms: 1000
    properties:
      request.timeout.ms: 100

server:
  incoming:
    port: 8081
  outgoing:
    port: 8082




