kind: Service
apiVersion: v1
metadata:
  name: realtime-dispatcher
spec:
  type: LoadBalancer
  ports:
  - name: incoming
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: realtime
    port: 8082
    targetPort: 8082
    protocol: TCP
  selector:
    app: realtime-dispatcher
