kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: realtime-dispatcher-dev
spec:
  replicas:
  template:
    metadata:
      name: realtime-dispatcher
      labels:
        app: realtime-dispatcher
        env: dev
    spec:
      containers:
      - name: infrastructure
        image: gcr.io/cloud-solutions-images/realtime-dispatcher:1.0.0
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        command: ["sh", "-c", "java -jar app.jar --server.port=8080"]