Master:
  InstallPlugins:
  - kubernetes:1.14.8
  - workflow-aggregator:2.5
  - workflow-job:2.32
  - credentials-binding:1.18
  - git:3.9.3
  - google-oauth-plugin:0.7
  - google-source-plugin:0.3
  Cpu: "1"
  Memory: "2048Mi"
  JavaOpts: "-Xms2048m -Xmx2048m"
  ServiceType: ClusterIP
Agent:
  Enabled: false
Persistence:
  Size: 50Gi
NetworkPolicy:
  ApiVersion: networking.k8s.io/v1
rbac:
  install: true
  serviceAccountName: cd-jenkins